apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mxjobs.qiniu.com
spec:
  group: qiniu.com
  names:
    kind: MXJob
    listKind: MXJobList
    plural: mxjobs
    singular: mxjob
  scope: Namespaced
  version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            replicaSpecs:
              required:
              - scheduler
              - server
              - worker
              properties:
                scheduler:
                  required:
                  - replicas
                  properties:
                    replicas:
                      type: integer
                      minimum: 1
                      maximum: 1
                    psRootPort:
                      type: integer
                    psVerbose:
                      type: integer
                      minimum: 1
                      maximum: 2
                server:
                  required:
                  - replicas
                  properties:
                    replicas:
                      type: integer
                      minimum: 1
                    psVerbose:
                      type: integer
                      minimum: 1
                      maximum: 2
                worker:
                  required:
                  - replicas
                  properties:
                    replicas:
                      type: integer
                      minimum: 1
                    psVerbose:
                      type: integer
                      minimum: 1
                      maximum: 2

